[package]
name = "retro-image"
description = "Decoder for image formats of retro computers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dev-dependencies]
png.workspace = true

[lints.rust]
# cargo-fuzz builds with `--cfg fuzzing`.
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fuzzing)"] }
