#!/usr/bin/env python3
"""Compares our format registry with RECOIL's format list.

Usage: scripts/coverage.py RECOIL_FORMATS_HTML > docs/coverage.md

RECOIL_FORMATS_HTML is a saved copy of https://recoil.sourceforge.net/formats.html
(a list of facts: platform, extensions, description). Our side comes from
`cargo run -q -p retro-image-cli -- --list-formats`.

A RECOIL row counts as covered when one of our formats on the same platform
claims one of its extensions. Where RECOIL has more rows than we have formats
for an extension on a platform, the rows are marked "check": the extension is
taken but we may not decode every variant.
"""

import collections
import html
import re
import subprocess
import sys

# RECOIL platform name -> ours.
PLATFORM_ALIASES = {
    "Atari ST/STE": "Atari ST",
    "Amiga DCTV": "Amiga",
    "Amiga HAM-E": "Amiga",
}


def recoil_rows(path):
    page = open(path, encoding="utf-8").read()
    table = page[page.index('<table class="formats">') :]
    for row in re.findall(r"<tr[^>]*>(.*?)</tr>", table, re.S)[1:]:
        cells = [
            html.unescape(re.sub("<[^>]+>", "", c)).strip()
            for c in re.findall(r"<td[^>]*>(.*?)</td>", row, re.S)
        ]
        platform, extensions, description = cells[:3]
        # "MIC+PMG+RP" -> main file MIC; "ART (arbitrary)" -> ART.
        exts = {
            e.split("+")[0].replace("(arbitrary)", "").strip().lower()
            for e in extensions.split(",")
        }
        yield platform, extensions, description, exts


def our_formats():
    out = subprocess.run(
        ["cargo", "run", "-q", "-p", "retro-image-cli", "--", "--list-formats"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    for line in out.splitlines():
        platform, name, exts, *_ = line.split("\t")
        yield platform, name, set(exts.split(","))


def main():
    ours = list(our_formats())
    claimed = collections.defaultdict(set)  # (platform, ext) -> our names
    for platform, name, exts in ours:
        for ext in exts:
            claimed[platform, ext].add(name)
    rows = list(recoil_rows(sys.argv[1]))
    rows_per_ext = collections.Counter(
        (PLATFORM_ALIASES.get(p, p), e) for p, _, _, exts in rows for e in exts
    )

    status = []
    for platform, extensions, description, exts in rows:
        ours_platform = PLATFORM_ALIASES.get(platform, platform)
        keys = [(ours_platform, e) for e in exts]
        names = set().union(*(claimed.get(k, set()) for k in keys))
        if not names:
            state = "no"
        elif any(rows_per_ext[k] > len(claimed.get(k, ())) for k in keys if k in claimed):
            state = "check"
        else:
            state = "yes"
        status.append((platform, extensions, description, state, names))

    counts = collections.Counter(s[3] for s in status)
    print("# Format coverage compared with RECOIL\n")
    print("Generated by `scripts/coverage.py` from RECOIL's")
    print("[format list](https://recoil.sourceforge.net/formats.html) and")
    print("`retro-image --list-formats`. Do not edit by hand.\n")
    print(f"- RECOIL formats: {len(status)}")
    print(f"- Covered: {counts['yes']}")
    print(f"- Extension taken, variant not confirmed (\"check\"): {counts['check']}")
    print(f"- Not covered: {counts['no']}")
    print(f"- Our registry entries: {len(ours)}\n")
    print("A row is covered when one of our formats on the same platform claims one")
    print("of its extensions; \"check\" means RECOIL lists more variants for that")
    print("extension than we register.\n")

    per_platform = collections.defaultdict(collections.Counter)
    for platform, _, _, state, _ in status:
        per_platform[platform][state] += 1
    print("## By platform\n")
    print("| Platform | Covered | Check | Missing |")
    print("|---|---:|---:|---:|")
    for platform in sorted(per_platform):
        c = per_platform[platform]
        print(f"| {platform} | {c['yes']} | {c['check']} | {c['no']} |")

    for state, title in (("no", "Not covered"), ("check", "Check")):
        print(f"\n## {title}\n")
        print("| Platform | Extensions | Description | Ours |")
        print("|---|---|---|---|")
        for platform, extensions, description, s, names in status:
            if s == state:
                print(f"| {platform} | {extensions} | {description} | {', '.join(sorted(names))} |")


if __name__ == "__main__":
    main()
