#!/usr/bin/env python3
"""Lists the supported formats, grouped by platform.

Usage: scripts/formats.py > docs/formats.md

Reads the format registry through `cargo run -q -p retro-image-cli -- --list-formats`.
"""

import collections
import subprocess


def main():
    out = subprocess.run(
        ["cargo", "run", "-q", "-p", "retro-image-cli", "--", "--list-formats"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    platforms = collections.defaultdict(list)
    for line in out.splitlines():
        platform, name, exts, flags = line.split("\t")
        platforms[platform].append((name, exts, flags.split(",") if flags else []))

    print("# Supported formats\n")
    print("Generated by `scripts/formats.py` from `retro-image --list-formats`.")
    print("Do not edit by hand.\n")
    print(f"{sum(map(len, platforms.values()))} formats on {len(platforms)} platforms.\n")
    print("A format marked under Detected has a signature, so it is also recognised")
    print("by content when the file has some other name. One marked under Companions")
    print("can pick up extra data, usually the palette, from a file next to it with")
    print("the same base name.\n")
    print("See [coverage.md](coverage.md) for a comparison with RECOIL's format list.\n")
    for platform in sorted(platforms):
        print(f"## {platform}\n")
        print("| Format | Extensions | Detected | Companions |")
        print("|---|---|:-:|:-:|")
        for name, exts, flags in platforms[platform]:
            exts = ", ".join(e.upper() for e in exts.split(",") if e) or "(by content)"
            detected = "yes" if "signature" in flags else ""
            companions = "yes" if "companions" in flags else ""
            print(f"| {name} | {exts} | {detected} | {companions} |")
        print()


if __name__ == "__main__":
    main()
